#! /bin/sh

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          38
bspc config top_padding         40
bspc config bottom_padding      10
bspc config left_padding        90
bspc config right_padding       90


bspc config split_ratio          0.501
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#8ec07c
bspc config normal_border_color \#689d6a

bspc rule -a vlc state=floating

setxkbmap -option grp:alt_shift_toggle us,ru &

bspc rule -a \*:"command" state=floating center=on rectangle=470x300+0+0
bspc rule -a \*:"fzfmenu" state=floating center=on sticky=on rectangle=470x300+0+0

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
