#!/bin/sh

$HOME/.config/polybar/launch.sh
wmname LG3D &
xset -dpms &
xset s off &
pgrep -x sxhkd >/dev/null || sxhkd &
setxkbmap -option grp:alt_shift_toggle us,ru &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 1
bspc config window_gap 15
bspc config normal_border_color \#333333
bspc config focused_border_color \#333333
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config single_monocle true

bspc rule -a Pavucontrol state=floating center=on sticky=off rectangle=800x500+25+55
bspc rule -a Galculator state=floating center=on sticky=off rectangle=280x400+25+55
bspc rule -a \*:"fzfmenu" state=floating center=on sticky=off rectangle=400x250+0+0
bspc rule -a \*:"command" state=floating center=on sticky=off rectangle=800x500+0+0
bspc rule -a \*:"pacmaninstall" state=floating center=on sticky=off rectangle=800x500+25+55
bspc rule -a \*:"nmconnect" state=floating center=on sticky=off rectangle=600x300+25+55
bspc rule -a \*:"record" state=floating center=on sticky=off rectangle=400x250+25+55
bspc rule -a \*:"blueman-manager" state=floating center=on sticky=off rectangle=550x350+25+55

# kitty -c ~/.config/kitty/kitty_t.conf --name start_clock tty-clock -C 7 -s -c
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
/home/konditer/.scripts/tgreboot
