
require('settings')
require('keymaps')
require('plugins')
require('lsp')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.lualine')
require('plugins.barbar')
require('plugins.nvim_comment')
require('plugins.toggleterm')
require('plugins.nvim-autopairs')
require('plugins.mason')
require('plugins.luasnip')
require('plugins.neotree')
require("plugins.none_ls")
require("plugins.prettier")
require("plugins.emmet")
require("plugins.trouble")
require("plugins.eslint")


